#!/usr/bin/env bash
set -euo pipefail

# Script to generate Version.swift with dynamic version information
# - Release builds: Show version from Formula/envpocket.rb
# - Debug builds: Show version + git hash

# Determine output file
OUTPUT_FILE="Sources/EnvPocket/Version.swift"

# Get version from Formula (supports both 'version "X.Y.Z"' and 'version X.Y.Z' formats)
VERSION=$(grep -E '^\s*version\s+' Formula/envpocket.rb | awk '{print $2}' || echo "0.0.0")

# Get git hash (short)
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Generate the Version.swift file
cat > "$OUTPUT_FILE" << EOF
//
//  Version.swift
//  EnvPocket
//
//  Auto-generated by scripts/generate-version.sh
//  DO NOT EDIT MANUALLY
//

import Foundation

enum Version {
    static let release = "$VERSION"
    static let gitHash = "$GIT_HASH"

    static var current: String {
        #if DEBUG
        return "\(release)-dev+\(gitHash)"
        #else
        return release
        #endif
    }
}
EOF

echo "✓ Generated $OUTPUT_FILE (version: $VERSION, git: $GIT_HASH)"
