name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on macOS
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Show Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --parallel
      
  build-release:
    name: Build Release Binary
    runs-on: macos-14
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
      
    - name: Build Release
      run: swift build -c release
      
    - name: Create artifact
      run: |
        cp .build/release/envpocket ./envpocket
        tar -czf envpocket-macos.tar.gz envpocket
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: envpocket-macos
        path: envpocket-macos.tar.gz